### PR TITLE
Fix Atlas help for packer navigation

### PR DESCRIPTION
**Pull request by burzinpatel**
Fix for HashiCorp/roadmap issue #1271.

Fixing incorrect relative path.

/cc: @pearkes

### CODE REVIEW

**Comment by burzinpatel** [comment]
@pearkes: please test/verify before merging (I had no way to test :)).

**Comment by handlers** [comment]
LGTM and works locally!

**Comment by sethvargo** [comment]
@handlers wanna pull this into Atlas please?

**Comment by handlers** [comment]
@sethvargo :+1:

**Pull request merged**
